[package]
authors = ["Paul Lange <palango@gmx.de>"]
name = "gdax"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
reqwest = "0.7.1"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
uuid = "0.5.1"
